version: '3.4'
 
services:
  backend-stage:
    image: backend-stage
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["-e stage"]
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - .:/app

  db-stage:
    image: postgres:15
    env_file:
     - .env.stage
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data-dev/

  files-stage:
    image: redis:7
    container_name: redis
    env_file:
      - .env.stage
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./redis/data/:/var/lib/redis/data/
      - ./docker/docker-service-redis-start.sh:/usr/local/bin/docker-service-redis-start.sh
    entrypoint: /usr/local/bin/docker-service-redis-start.sh # used to pass PW from environment variable change things there if needed
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  localstack-stage:
    image: localstack/localstack
    container_name: localstack-aws-stage
    volumes:
      - ./localstack/:/var/lib/localstack
    env_file:
      - .env.stage
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_PERSISTENCE=1
    ports:
      - "127.0.0.1:4566:4566"